import type { InputDefinition, ModelDefinition, ModelWorkflow, ParameterDefinition, WorkflowDefinition, WorkflowId } from "./types";

export const WORKFLOWS: WorkflowDefinition[] = [
  { id: "text-to-image", label: "Texto → Imagen", shortLabel: "Texto → Imagen", description: "Creá una imagen desde una descripción.", output: "image" },
  { id: "image-to-image", label: "Imagen → Imagen", shortLabel: "Imagen → Imagen", description: "Transformá o combiná una o varias imágenes.", output: "image" },
  { id: "image-inpaint", label: "Imagen + máscara → Imagen", shortLabel: "Inpainting", description: "Editá solamente la zona indicada por una máscara.", output: "image" },
  { id: "text-to-video", label: "Texto → Video", shortLabel: "Texto → Video", description: "Generá movimiento, cámara y escena desde texto.", output: "video" },
  { id: "image-to-video", label: "Imagen → Video", shortLabel: "Imagen → Video", description: "Animá un frame inicial o referencias visuales.", output: "video" },
  { id: "video-to-video", label: "Video → Video", shortLabel: "Video → Video", description: "Continuá, controlá o transformá un video.", output: "video" },
  { id: "audio-to-video", label: "Audio → Video", shortLabel: "Audio → Video", description: "Creá video guiado por voz, música o una pista completa.", output: "video" },
  { id: "character-animation", label: "Personaje + actuación → Video", shortLabel: "Animar personaje", description: "Transferí movimiento y expresión a un personaje.", output: "video" },
  { id: "text-to-speech", label: "Texto → Voz", shortLabel: "Texto → Voz", description: "Diseñá una voz y sintetizá el texto.", output: "audio" },
  { id: "voice-clone", label: "Texto + voz → Voz", shortLabel: "Clonar voz", description: "Sintetizá texto con una o dos voces de referencia.", output: "audio" },
  { id: "text-to-sound", label: "Texto → Sonido", shortLabel: "Texto → Sonido", description: "Generá efectos, foley y ambientes.", output: "audio" },
  { id: "audio-to-audio", label: "Audio → Audio", shortLabel: "Audio → Audio", description: "Editá, continuá, convertí o repintá audio.", output: "audio" },
  { id: "text-to-music", label: "Texto → Música", shortLabel: "Texto → Música", description: "Generá canciones o instrumentales desde concepto y letra.", output: "audio" },
  { id: "audio-to-music", label: "Audio → Música", shortLabel: "Audio → Música", description: "Hacé covers o transferencias de timbre musical.", output: "audio" },
];

const image = (key: string, label: string, help: string, required = true, multiple = false, max?: number): InputDefinition => ({ key, label, help, accept: "image/*", required, multiple, max });
const video = (key: string, label: string, help: string, required = true, multiple = false, max?: number): InputDefinition => ({ key, label, help, accept: "video/*", required, multiple, max });
const audio = (key: string, label: string, help: string, required = true, multiple = false, max?: number): InputDefinition => ({ key, label, help, accept: "audio/*", required, multiple, max });
const wf = (id: WorkflowId, task: string, inputs: InputDefinition[], defaults: ModelWorkflow["defaults"]): ModelWorkflow => ({ id, task, inputs, defaults });

const commonVisual: ParameterDefinition[] = [
  { key: "resolution", label: "Resolución", type: "select", options: ["512x512", "832x480", "768x432", "1024x1024", "1280x720", "1280x704"].map((value) => ({ label: value, value })) },
  { key: "num_inference_steps", label: "Pasos", type: "number", min: 1, max: 100, step: 1 },
  { key: "guidance_scale", label: "Guidance", type: "number", min: 0, max: 30, step: 0.1 },
  { key: "seed", label: "Seed", type: "number", min: -1, step: 1 },
  { key: "batch_size", label: "Cantidad", type: "number", min: 1, max: 8, step: 1 },
  { key: "flow_shift", label: "Flow shift", type: "number", min: 0, max: 30, step: 0.1 },
  { key: "denoising_strength", label: "Fuerza de transformación", type: "number", min: 0, max: 1, step: 0.05 },
];
const fixedStepVisual = commonVisual.filter((parameter) => !["num_inference_steps", "guidance_scale"].includes(parameter.key));
const videoParams: ParameterDefinition[] = [...commonVisual, { key: "video_length", label: "Frames", type: "number", min: 1, max: 1201, step: 1 }, { key: "force_fps", label: "FPS", type: "number", min: 1, max: 60, step: 1 }];
const fixedStepVideo = videoParams.filter((parameter) => !["num_inference_steps", "guidance_scale", "flow_shift"].includes(parameter.key));
const audioParams: ParameterDefinition[] = [
  { key: "duration_seconds", label: "Duración (segundos)", type: "number", min: 1, max: 300, step: 1 },
  { key: "num_inference_steps", label: "Pasos", type: "number", min: 1, max: 100, step: 1 },
  { key: "guidance_scale", label: "Guidance", type: "number", min: 0, max: 30, step: 0.1 },
  { key: "seed", label: "Seed", type: "number", min: -1, step: 1 },
  { key: "temperature", label: "Temperatura", type: "number", min: 0, max: 2, step: 0.05 },
  { key: "top_p", label: "Top P", type: "number", min: 0, max: 1, step: 0.05 },
  { key: "top_k", label: "Top K", type: "number", min: 0, max: 200, step: 1 },
  { key: "repeat_generation", label: "Penalización de repetición", type: "number", min: 0, max: 3, step: 0.05 },
];
const language: ParameterDefinition = { key: "model_mode", label: "Idioma", type: "select", options: ["auto", "spanish", "english", "chinese", "french", "german", "italian", "japanese", "korean", "portuguese", "russian"].map((value) => ({ label: value, value })) };
const wanSolver: ParameterDefinition = { key: "sample_solver", label: "Sampler", type: "select", options: [{ label: "UniPC", value: "unipc" }, { label: "Euler", value: "euler" }, { label: "DPM++", value: "dpm++" }, { label: "FlowMatch CausVid", value: "causvid" }, { label: "LCM + LTX", value: "lcm" }] };
const h3Solver: ParameterDefinition = { key: "sample_solver", label: "Sampler", type: "select", options: [{ label: "Euler", value: "euler" }, { label: "RES Multistep", value: "res_multistep" }] };
const qwenImageSolver: ParameterDefinition = { key: "sample_solver", label: "Sampler", type: "select", options: [{ label: "Default", value: "default" }, { label: "Lightning", value: "lightning" }] };
const stableAudioSolver: ParameterDefinition = { key: "sample_solver", label: "Sampler", type: "select", options: [{ label: "PingPong", value: "pingpong" }, { label: "Euler", value: "euler" }, { label: "DPM++", value: "dpmpp" }, { label: "RK4", value: "rk4" }] };
const speechEnhancer: ParameterDefinition = { key: "prompt_enhancer", label: "Formato de voz", type: "select", help: "Voz continua o diálogo con turnos.", options: [{ label: "Voz", value: "T" }, { label: "Diálogo", value: "T1" }] };
const stableAudioMode: ParameterDefinition = { key: "audio_prompt_type", label: "Operación de audio", type: "select", options: [{ label: "Generar desde texto", value: "" }, { label: "Editar audio", value: "AE" }, { label: "Inpainting de audio", value: "AI" }, { label: "Continuar audio", value: "AC" }] };
const aceAudioMode: ParameterDefinition = { key: "audio_prompt_type", label: "Uso de referencias", type: "select", options: [{ label: "Generar desde texto o letra", value: "" }, { label: "Cover", value: "A" }, { label: "Transferencia de timbre", value: "B" }, { label: "Cover + timbre", value: "AB" }] };
const maskMode = (workflows: WorkflowId[], extended = false): ParameterDefinition => ({ key: "mask_preprocess", label: "Tratamiento de máscara", type: "select", workflows, options: [{ label: "Sin máscara", value: "" }, { label: "Zona A", value: "A" }, { label: "Inversa (NA)", value: "NA" }, ...(extended ? ["XA", "XNA", "YA", "YNA", "WA", "WNA", "ZA", "ZNA"].map((value) => ({ label: value, value })) : [])] });
const ltxGuide: ParameterDefinition = { key: "guide_preprocess", label: "Control de video", type: "select", workflows: ["video-to-video"], options: [{ label: "Sin control", value: "" }, { label: "Movimiento humano", value: "PVG" }, { label: "Movimiento + alineación de pose", value: "OVG" }, { label: "Profundidad", value: "DVG" }, { label: "Bordes Canny", value: "EVG" }, { label: "Control crudo / IC-LoRA", value: "VG" }, { label: "Inpainting", value: "MVG" }, { label: "Hoja de referencias", value: "I" }, { label: "SDR a HDR", value: "V&G" }, { label: "Inyectar frames", value: "KFI" }] };
const h3FlGuide: ParameterDefinition = { key: "guide_preprocess", label: "Uso del video", type: "select", workflows: ["video-to-video"], options: [{ label: "Sin control", value: "" }, { label: "Video de control", value: "GV" }, { label: "Inyectar frames", value: "KFI" }] };
const h3RefGuide: ParameterDefinition = { key: "guide_preprocess", label: "Uso del video", type: "select", workflows: ["video-to-video"], options: [{ label: "Sin video", value: "" }, { label: "Una referencia", value: "V-" }, { label: "Dos referencias", value: "V+-" }, { label: "Transferir profundidad", value: "DV" }, { label: "Control genérico", value: "V" }] };
const vaceGuide: ParameterDefinition = { key: "guide_preprocess", label: "Preprocesamiento de control", type: "select", workflows: ["video-to-video"], options: [{ label: "Formato VACE crudo", value: "V" }, ...["UV", "PV", "OV", "DV", "SV", "LV", "CV", "MV", "PDV", "PSV", "PLV", "DSV", "DLV", "SLV"].map((value) => ({ label: value, value }))] };
const imageRefMode = (workflows: WorkflowId[], positioned = false): ParameterDefinition => ({ key: "image_ref_mode", label: "Semántica de referencias", type: "select", workflows, options: [{ label: "Personas u objetos", value: "I" }, { label: "Primera: escena/sujeto principal", value: "KI" }, ...(positioned ? [{ label: "Frames posicionados + objetos", value: "FI" }] : [])] });
const framesPositions: ParameterDefinition = { key: "frames_positions", label: "Posiciones de frames", type: "text", help: "Números de frame separados por espacios; L significa el último frame.", workflows: ["image-to-video", "video-to-video"] };
const promptEnhancer = (options: { label: string; value: string }[], workflows: WorkflowId[]): ParameterDefinition => ({ key: "prompt_enhancer", label: "Mejora automática del prompt", type: "select", workflows, options: [{ label: "Desactivada", value: "" }, ...options] });

export const MODELS: ModelDefinition[] = [
  { id: "ti2v_2_2", name: "Wan 2.2 TI2V 5B", family: "Wan 2.2", summary: "Texto, imagen inicial o continuación de video en un modelo compacto.", tier: "Rápido", license: "Apache 2.0", accent: "#ff6b45", parameters: [...videoParams, wanSolver], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "1280x720", video_length: 121, num_inference_steps: 50, guidance_scale: 5, sample_solver: "unipc", flow_shift: 5, image_prompt_type: "" }),
    wf("image-to-video", "video.generate", [image("image_start", "Frame inicial", "La escena desde la que comenzará el video.")], { resolution: "1280x720", video_length: 121, num_inference_steps: 50, guidance_scale: 5, sample_solver: "unipc", flow_shift: 5, image_prompt_type: "S" }),
    wf("video-to-video", "video.edit", [video("video_source", "Video a continuar", "El final de este video se usa como punto de partida.")], { resolution: "1280x720", video_length: 121, num_inference_steps: 50, guidance_scale: 5, sample_solver: "unipc", flow_shift: 5, image_prompt_type: "V" }),
  ] },
  { id: "ti2v_2_2_fastwan", name: "Wan 2.2 TI2V 5B FastWan", family: "Wan 2.2", summary: "Variante acelerada de tres pasos para iteraciones de video mucho más rápidas.", tier: "Rápido", license: "Apache 2.0", accent: "#ff8a45", parameters: [...videoParams, wanSolver], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "1280x720", video_length: 121, num_inference_steps: 3, guidance_scale: 1, sample_solver: "unipc", flow_shift: 3, image_prompt_type: "T" }),
    wf("image-to-video", "video.generate", [image("image_start", "Frame inicial", "La escena desde la que comenzará el video.")], { resolution: "1280x720", video_length: 121, num_inference_steps: 3, guidance_scale: 1, sample_solver: "unipc", flow_shift: 3, image_prompt_type: "S" }),
    wf("video-to-video", "video.edit", [video("video_source", "Video a continuar", "El final de este video se usa como punto de partida.")], { resolution: "1280x720", video_length: 121, num_inference_steps: 3, guidance_scale: 1, sample_solver: "unipc", flow_shift: 3, image_prompt_type: "V" }),
  ] },
  { id: "ltx2_25_22B_distilled", name: "LTX‑2.5 Distilled 22B", family: "LTX‑2.5", summary: "Generación conjunta de imagen, video y audio con controles multimodales.", tier: "Equilibrado", license: "LTX Community", accent: "#7e6cf2", parameters: [...videoParams, ltxGuide, maskMode(["video-to-video"]), framesPositions, promptEnhancer([{ label: "Desde texto", value: "T" }, { label: "Texto + imagen inicial", value: "TI" }, { label: "Relato desde texto", value: "T1" }, { label: "Relato + imagen inicial", value: "TI1" }], ["text-to-video", "image-to-video"])], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "1280x704", video_length: 241, num_inference_steps: 8, flow_shift: 5, image_prompt_type: "", video_prompt_type: "", audio_prompt_type: "" }),
    wf("image-to-video", "video.generate", [image("image_start", "Frame inicial", "Primer frame del video."), image("image_end", "Frame final", "Destino visual opcional.", false), image("image_refs", "Referencia o frame inyectado", "LTX admite una imagen adicional como referencia, fondo o frame posicionado.", false)], { resolution: "1280x704", video_length: 241, num_inference_steps: 8, image_prompt_type: "S", video_prompt_type: "", audio_prompt_type: "" }),
    wf("video-to-video", "video.edit", [video("video_guide", "Video de control", "Movimiento o contenido que guiará el resultado."), video("video_mask", "Máscara de video", "Máscara temporal opcional.", false), image("image_refs", "Referencia o frame inyectado", "Imagen opcional para hoja de referencias o inyección de frames.", false)], { resolution: "1280x704", video_length: 241, num_inference_steps: 8, guide_preprocess: "VG", mask_preprocess: "", image_ref_mode: "", audio_prompt_type: "" }),
    wf("audio-to-video", "video.generate", [audio("audio_guide", "Pista de audio", "Soundtrack, voz o ritmo que guía el video.")], { resolution: "1280x704", video_length: 241, num_inference_steps: 8, audio_prompt_type: "A" }),
    wf("text-to-image", "image.generate", [], { resolution: "1024x1024", video_length: 1, num_inference_steps: 8, image_prompt_type: "", video_prompt_type: "" }),
    wf("image-to-image", "image.edit", [image("image_refs", "Referencia", "LTX‑2.5 admite una sola imagen de referencia semántica.")], { resolution: "1024x1024", video_length: 1, num_inference_steps: 8, video_prompt_type: "I" }),
  ] },
  { id: "minimax_h3_fl2va_pruned", name: "MiniMax H3 FL2VA Pruned 20B", family: "MiniMax H3", summary: "Video con audio estéreo, primer/último frame y control audiovisual.", tier: "Avanzado", license: "H3 Community", accent: "#1f9d7a", parameters: [...videoParams, h3Solver, h3FlGuide, maskMode(["video-to-video"]), framesPositions, promptEnhancer([{ label: "Prompt H3 desde texto", value: "T" }, { label: "Prompt H3 desde texto + imagen", value: "TI" }], ["text-to-video", "image-to-video"])], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "832x480", video_length: 124, num_inference_steps: 20, guidance_scale: 1, sample_solver: "euler", flow_shift: 12 }),
    wf("image-to-video", "video.generate", [image("image_start", "Primer frame", "Inicio visual del video."), image("image_end", "Último frame", "Final visual opcional.", false)], { resolution: "832x480", video_length: 124, num_inference_steps: 20, image_prompt_type: "S" }),
    wf("video-to-video", "video.edit", [video("video_guide", "Video de control", "Guía de movimiento o contenido."), video("video_mask", "Máscara", "Máscara temporal opcional.", false), image("image_refs", "Frames a inyectar", "Imágenes opcionales asociadas a posiciones de frame.", false, true, 8)], { resolution: "832x480", video_length: 124, num_inference_steps: 20, guide_preprocess: "GV", mask_preprocess: "" }),
    wf("audio-to-video", "video.generate", [audio("audio_guide", "Pista de audio", "Audio que guiará el resultado.")], { resolution: "832x480", video_length: 124, num_inference_steps: 20, audio_prompt_type: "A" }),
  ] },
  { id: "minimax_h3_fl2va_pruned_turbo_8", name: "MiniMax H3 FL2VA Turbo 8", summary: "El mismo checkpoint FL2VA con la LoRA Turbo de Lightx2v: ocho pasos fijos, sin guidance. Denoising 2.2× más rápido que la base en esta RTX 2060.", family: "MiniMax H3", tier: "Rápido", license: "H3 Community", accent: "#2bb58f", parameters: [...fixedStepVideo, h3FlGuide, maskMode(["video-to-video"]), framesPositions, promptEnhancer([{ label: "Prompt H3 desde texto", value: "T" }, { label: "Prompt H3 desde texto + imagen", value: "TI" }], ["text-to-video", "image-to-video"])], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "832x480", video_length: 124, num_inference_steps: 8, guidance_scale: 1 }),
    wf("image-to-video", "video.generate", [image("image_start", "Primer frame", "Inicio visual del video."), image("image_end", "Último frame", "Final visual opcional.", false)], { resolution: "832x480", video_length: 124, num_inference_steps: 8, image_prompt_type: "S" }),
    wf("video-to-video", "video.edit", [video("video_guide", "Video de control", "Guía de movimiento o contenido."), video("video_mask", "Máscara", "Máscara temporal opcional.", false), image("image_refs", "Frames a inyectar", "Imágenes opcionales asociadas a posiciones de frame.", false, true, 8)], { resolution: "832x480", video_length: 124, num_inference_steps: 8, guide_preprocess: "GV", mask_preprocess: "" }),
    wf("audio-to-video", "video.generate", [audio("audio_guide", "Pista de audio", "Audio que guiará el resultado.")], { resolution: "832x480", video_length: 124, num_inference_steps: 8, audio_prompt_type: "A" }),
  ] },
  { id: "minimax_h3_fl2va_pruned_turbo_4", name: "MiniMax H3 FL2VA Turbo 4", summary: "Cuatro pasos fijos con la LoRA Turbo 768p. Para previsualizar; el audio puede salir con ruido y todavía no se probó en esta máquina.", family: "MiniMax H3", tier: "Rápido", license: "H3 Community", accent: "#2bb58f", parameters: [...fixedStepVideo, h3FlGuide, maskMode(["video-to-video"]), framesPositions, promptEnhancer([{ label: "Prompt H3 desde texto", value: "T" }, { label: "Prompt H3 desde texto + imagen", value: "TI" }], ["text-to-video", "image-to-video"])], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "832x480", video_length: 124, num_inference_steps: 4, guidance_scale: 1 }),
    wf("image-to-video", "video.generate", [image("image_start", "Primer frame", "Inicio visual del video."), image("image_end", "Último frame", "Final visual opcional.", false)], { resolution: "832x480", video_length: 124, num_inference_steps: 4, image_prompt_type: "S" }),
    wf("video-to-video", "video.edit", [video("video_guide", "Video de control", "Guía de movimiento o contenido."), video("video_mask", "Máscara", "Máscara temporal opcional.", false), image("image_refs", "Frames a inyectar", "Imágenes opcionales asociadas a posiciones de frame.", false, true, 8)], { resolution: "832x480", video_length: 124, num_inference_steps: 4, guide_preprocess: "GV", mask_preprocess: "" }),
    wf("audio-to-video", "video.generate", [audio("audio_guide", "Pista de audio", "Audio que guiará el resultado.")], { resolution: "832x480", video_length: 124, num_inference_steps: 4, audio_prompt_type: "A" }),
  ] },
  { id: "minimax_h3_ref2va_pruned", name: "MiniMax H3 Ref2VA Pruned 20B", family: "MiniMax H3", summary: "Video y audio con múltiples sujetos, videos y voces de referencia.", tier: "Avanzado", license: "H3 Community", accent: "#1f9d7a", parameters: [...videoParams, h3Solver, h3RefGuide, imageRefMode(["image-to-video"]), promptEnhancer([{ label: "Prompt de referencias desde texto", value: "T" }, { label: "Prompt desde texto + primera referencia", value: "TI" }], ["image-to-video"])], workflows: [
    wf("image-to-video", "video.generate", [image("image_primary", "Escena o sujeto principal", "Esta imagen ocupa la primera posición y define la composición base."), image("image_refs", "Personas u objetos adicionales", "Referencias complementarias; entre ellas el orden no cambia su función.", false, true, 5)], { resolution: "832x480", video_length: 124, num_inference_steps: 20, guidance_scale: 1, sample_solver: "euler", flow_shift: 12, image_ref_mode: "KI" }),
    wf("video-to-video", "video.edit", [video("video_refs", "Videos de referencia", "Uno o dos videos de referencia.", true, true, 2)], { resolution: "832x480", video_length: 124, num_inference_steps: 20, guide_preprocess: "V" }),
    wf("audio-to-video", "video.generate", [audio("audio_guide", "Primera referencia de voz", "Voz o soundtrack principal."), audio("audio_guide2", "Segunda referencia", "Segunda voz opcional.", false)], { resolution: "832x480", video_length: 124, num_inference_steps: 20, audio_prompt_type: "AB" }),
  ] },
  { id: "vace_14B", name: "Wan VACE 14B", family: "Wan 2.1", summary: "Control, referencias, inpainting, pose, profundidad y reemplazo.", tier: "Especialista", license: "Apache 2.0", accent: "#e2608d", parameters: [...videoParams, wanSolver, vaceGuide, maskMode(["video-to-video"], true), imageRefMode(["image-to-video", "image-to-image", "video-to-video"], true), framesPositions], workflows: [
    wf("text-to-video", "video.generate", [], { resolution: "832x480", video_length: 81, num_inference_steps: 30, sample_solver: "unipc", flow_shift: 5 }),
    wf("image-to-video", "video.generate", [image("image_primary", "Escena o sujeto principal", "VACE la recibe primero como composición base; no es necesariamente el primer frame del video."), image("image_refs", "Personas u objetos adicionales", "Referencias complementarias; entre ellas el orden no cambia su función.", false, true, 7)], { resolution: "832x480", video_length: 81, num_inference_steps: 30, sample_solver: "unipc", image_ref_mode: "KI" }),
    wf("video-to-video", "video.edit", [video("video_guide", "Video de control", "Video crudo, pose, profundidad, bordes u otro control."), video("video_mask", "Máscara de video", "Área editable opcional.", false), image("image_refs", "Referencias adicionales", "Personas, objetos o frames posicionados.", false, true, 8)], { resolution: "832x480", video_length: 81, num_inference_steps: 30, guide_preprocess: "V", mask_preprocess: "", image_ref_mode: "" }),
    wf("text-to-image", "image.generate", [], { resolution: "1024x1024", video_length: 1, num_inference_steps: 30 }),
    wf("image-to-image", "image.edit", [image("image_refs", "Referencias", "Imágenes condicionantes.", true, true, 8)], { resolution: "1024x1024", video_length: 1, num_inference_steps: 30, image_ref_mode: "I" }),
  ] },
  { id: "animate2", name: "Wan 2.2 Animate 2 14B", family: "Wan 2.2", summary: "Transfiere movimiento, expresión y cámara a un personaje.", tier: "Especialista", license: "Apache 2.0", accent: "#e2608d", parameters: [...videoParams, wanSolver], workflows: [wf("character-animation", "character.animate", [image("image_refs", "Personaje", "Imagen limpia del personaje."), video("video_guide", "Video de actuación", "Movimiento, expresión y cámara a transferir.")], { resolution: "832x480", video_length: 65, num_inference_steps: 40, guidance_scale: 3, sample_solver: "dpm++", guide_preprocess: "UV", image_ref_mode: "I", image_prompt_type: "" })] },
  { id: "z_image", name: "Z‑Image Turbo 6B", family: "Z‑Image", summary: "Texto a imagen veloz en ocho pasos.", tier: "Rápido", license: "Apache 2.0", accent: "#e2a72e", parameters: commonVisual, workflows: [wf("text-to-image", "image.generate", [], { resolution: "1024x1024", num_inference_steps: 8, guidance_scale: 0, batch_size: 1 })] },
  { id: "qwen_image_20B", name: "Qwen Image 20B", family: "Qwen", summary: "Composición compleja, texto legible e inpainting de alta calidad.", tier: "Avanzado", license: "Apache 2.0", accent: "#e2a72e", parameters: [...commonVisual, qwenImageSolver, { key: "model_mode", label: "Método de inpainting", type: "select", workflows: ["image-inpaint"], options: [2, 3, 4, 5].map((value) => ({ label: `LanPaint ${[2, 5, 10, 15][value - 2]} pasos`, value })) }, { key: "masking_strength", label: "Fuerza de máscara", type: "number", workflows: ["image-inpaint"], min: 0, max: 1, step: 0.05 }], workflows: [
    wf("text-to-image", "image.generate", [], { resolution: "1280x720", num_inference_steps: 20, guidance_scale: 4, sample_solver: "default", batch_size: 1 }),
    wf("image-inpaint", "image.edit", [image("image_guide", "Imagen a editar", "La imagen base completa."), image("image_mask", "Máscara", "Blanco indica la zona que se vuelve a generar.")], { resolution: "1024x1024", num_inference_steps: 20, guidance_scale: 4, sample_solver: "default", video_prompt_type: "VA", model_mode: 2, denoising_strength: 1, masking_strength: 1 }),
  ] },
  { id: "qwen_image_edit_plus_20B", name: "Qwen Image Edit Plus", family: "Qwen", summary: "Edición conversacional, composición multi‑referencia e inpainting.", tier: "Especialista", license: "Apache 2.0", accent: "#e2608d", parameters: [...commonVisual, qwenImageSolver, { key: "model_mode", label: "Método de edición", type: "select", options: [{ label: "Denoising con máscara", value: 0 }, { label: "LoRA: contenido nuevo", value: 1 }, { label: "LanPaint 2 pasos", value: 2 }, { label: "LanPaint 5 pasos", value: 3 }, { label: "LanPaint 10 pasos", value: 4 }, { label: "LanPaint 15 pasos", value: 5 }] }, { key: "masking_strength", label: "Fuerza de máscara", type: "number", workflows: ["image-inpaint"], min: 0, max: 1, step: 0.05 }], workflows: [
    wf("image-to-image", "image.edit", [image("image_primary", "Imagen principal", "Escena o sujeto que Qwen editará; siempre se envía en la primera posición."), image("image_refs", "Referencias adicionales", "Personas, objetos o estilos que se incorporan como apoyo.", false, true, 7)], { resolution: "1024x1024", num_inference_steps: 20, guidance_scale: 4, sample_solver: "default", video_prompt_type: "KI", denoising_strength: 1, model_mode: 0, batch_size: 1 }),
    wf("image-inpaint", "image.edit", [image("image_guide", "Imagen a editar", "La imagen base completa."), image("image_mask", "Máscara", "Blanco indica la zona editable."), image("image_refs", "Referencias adicionales", "Personas u objetos que deben guiar el relleno.", false, true, 7)], { resolution: "1024x1024", num_inference_steps: 20, guidance_scale: 4, sample_solver: "default", video_prompt_type: "VAG", model_mode: 1, denoising_strength: 1, masking_strength: 1 }),
  ] },
  { id: "qwen_image_edit_plus_20B_lightning_8", name: "Qwen Image Edit Plus Lightning 8", family: "Qwen", summary: "La calidad multi‑referencia de Qwen Edit con una LoRA estable de ocho pasos, sin kernels Nunchaku.", tier: "Rápido", license: "Apache 2.0", accent: "#d66a9c", parameters: fixedStepVisual, workflows: [
    wf("image-to-image", "image.edit", [image("image_primary", "Imagen principal", "Escena o sujeto que Qwen editará; siempre se envía en la primera posición."), image("image_refs", "Referencias adicionales", "Personas, objetos o estilos que se incorporan como apoyo.", false, true, 7)], { resolution: "1024x1024", num_inference_steps: 8, guidance_scale: 1, sample_solver: "default", video_prompt_type: "KI", denoising_strength: 1, model_mode: 0, batch_size: 1 }),
  ] },
  { id: "qwen_image_edit_plus_20B_nunchaku_r128_int4", name: "Qwen Image Edit Plus Fast INT4", family: "Qwen", summary: "Checkpoint Nunchaku INT4 de cuatro pasos. Experimental en RTX 20: en esta RTX 2060 el kernel actual es inestable; usá Qwen estándar.", tier: "Rápido", license: "Apache 2.0", accent: "#d84f86", parameters: [...commonVisual, qwenImageSolver], workflows: [
    wf("image-to-image", "image.edit", [image("image_primary", "Imagen principal", "Escena o sujeto que Qwen editará; siempre se envía en la primera posición."), image("image_refs", "Referencias adicionales", "Personas, objetos o estilos que se incorporan como apoyo.", false, true, 7)], { resolution: "1024x1024", num_inference_steps: 4, guidance_scale: 1, sample_solver: "default", video_prompt_type: "KI", denoising_strength: 1, model_mode: 0, batch_size: 1 }),
  ] },
  { id: "qwen3_tts_base", name: "Qwen3‑TTS Base 1.7B", family: "Qwen3‑TTS", summary: "Síntesis y diálogo con una o dos voces de referencia.", tier: "Rápido", license: "Apache 2.0", accent: "#3d83d5", parameters: [...audioParams, language, speechEnhancer], workflows: [wf("voice-clone", "speech.clone", [audio("audio_guide", "Voz de referencia", "Muestra clara de la voz principal."), audio("audio_guide2", "Segunda voz", "Referencia opcional para diálogo.", false)], { duration_seconds: 30, temperature: .9, top_k: 50, repeat_generation: 1, audio_prompt_type: "A", model_mode: "auto", prompt_enhancer: "T" })] },
  { id: "qwen3_tts_voicedesign", name: "Qwen3‑TTS Voice Design", family: "Qwen3‑TTS", summary: "Diseña una voz nueva con lenguaje natural y sintetiza el texto.", tier: "Especialista", license: "Apache 2.0", accent: "#3d83d5", parameters: [...audioParams, language, speechEnhancer], workflows: [wf("text-to-speech", "speech.design", [], { duration_seconds: 30, temperature: .9, top_k: 50, repeat_generation: 1, model_mode: "spanish", prompt_enhancer: "T" })] },
  { id: "seedvc", name: "SeedVC", family: "SeedVC", summary: "Convierte voz o canto preservando la interpretación.", tier: "Especialista", license: "Checkpoint comunitario", accent: "#a969d8", parameters: [], workflows: [wf("audio-to-audio", "audio.convert", [audio("audio_source", "Interpretación original", "Audio cuyo ritmo e interpretación se conservan."), audio("voice_reference", "Voz destino", "Muestra de la voz que reemplazará a la original.")], {})] },
  { id: "stable_audio3_small_sfx", name: "Stable Audio 3 Small SFX", family: "Stable Audio", summary: "Foley, ambientes, edición, inpainting y continuación de audio.", tier: "Rápido", license: "Stability Community", accent: "#a969d8", parameters: [...audioParams, stableAudioSolver, { ...stableAudioMode, workflows: ["audio-to-audio"] }], workflows: [
    wf("text-to-sound", "sound.generate", [], { duration_seconds: 8, num_inference_steps: 8, guidance_scale: 1, sample_solver: "pingpong", audio_prompt_type: "" }),
    wf("audio-to-audio", "audio.edit", [audio("audio_guide", "Audio original", "Pista a editar, repintar o continuar.")], { duration_seconds: 8, num_inference_steps: 8, guidance_scale: 1, sample_solver: "pingpong", audio_prompt_type: "AE" }),
  ] },
  { id: "ace_step_v1_5", name: "ACE‑Step 1.5 Turbo", family: "ACE‑Step", summary: "Canciones, instrumentales, covers y transferencia de timbre.", tier: "Rápido", license: "MIT", accent: "#d86542", parameters: [...audioParams, { ...aceAudioMode, workflows: ["audio-to-music"] }], workflows: [
    wf("text-to-music", "music.generate", [], { duration_seconds: 120, num_inference_steps: 8, guidance_scale: 1, temperature: .85, top_p: .9, top_k: 0, repeat_generation: 1, audio_prompt_type: "" }),
    wf("audio-to-music", "music.edit", [audio("audio_guide", "Canción o timbre de referencia", "Fuente para cover o transferencia de timbre."), audio("audio_guide2", "Segunda referencia", "Timbre adicional opcional.", false)], { duration_seconds: 120, num_inference_steps: 8, guidance_scale: 1, audio_prompt_type: "A" }),
  ] },
];

export function modelsForWorkflow(workflow: WorkflowId) {
  return MODELS.filter((model) => model.workflows.some((item) => item.id === workflow));
}

export function workflowFor(model: ModelDefinition, workflow: WorkflowId) {
  return model.workflows.find((item) => item.id === workflow) ?? model.workflows[0];
}
